library(ggplot2)

setwd("F:\\Users\\Janis\\VIKA\\data\\")
lstData = list.files(pattern="*.csv")

# year = 2019
# month = formatC(seq(1, 12), width=2, flag=0)
# day = formatC(seq(1, 31), width=2, flag=0)
# dat = read.csv(grep("main", lstData, value = TRUE), header = TRUE, sep = ",")

colNamesKHW  = c("timestamp", "gridToBattery", "gridToConsumers", "PVToBattery", "PVToGrid", "PVToConsumers", "batteryToConsumers", "batteryToGrid", "gensetToConsumers", "gensetToBattery", "gas")
datKWH = read.csv(grep("kwh", lstData, value = TRUE), skip = 2, header = FALSE, col.names = colNamesKHW, sep = ",")

# convert timestamp class from factor to POSIXct
datKWH$timestamp <- as.POSIXct(strptime(datKWH$timestamp, format="%Y-%m-%d %H:%M:%S"))

# replace NA values with 0
datKWH[is.na(datKWH)] <- 0

print(head(datKWH))

g = ggplot(datKWH, aes(x = datKWH[, 'timestamp'], y = datKWH[, 'gridToBattery'])) 
g = g + geom_point() + geom_line()
g = g + ggtitle("Power generated by solar in January 2019") + xlab("Time") + ylab("Grid To Battery, kWh")
# Change the appearance of the main title
g = g + theme(plot.title = element_text(size=18, face="bold",margin = margin(10, 0, 10, 0)))
# scale_*_datetime for datetimes (class POSIXct),
g = g + scale_x_datetime(breaks='1 week', labels = "%W")
g = g + coord_cartesian(ylim = c(0, max(datKWH[, 'gridToBattery'])))