# to get all libraries at once just install the whole tidyverse
library(ggplot2)
library(lubridate)
library(dplyr)

setwd("F:\\Users\\Janis\\VIKA\\data\\")
lstData = list.files(pattern="*.csv")

colNamesKHW  = c("timestamp", "gridToBattery", "gridToConsumers", "PVToBattery", "PVToGrid", "PVToConsumers", "batteryToConsumers", "batteryToGrid", "gensetToConsumers", "gensetToBattery", "gas")
datKWH = read.csv(grep("kwh", lstData, value = TRUE), skip = 2, header = FALSE, col.names = colNamesKHW, sep = ",")

# convert timestamp class from factor to POSIXct
datKWH$timestamp <- as.POSIXct(strptime(datKWH$timestamp, format="%Y-%m-%d %H:%M:%S"))

# replace NA values with 0
datKWH[is.na(datKWH)] <- 0

timestamp = datKWH$timestamp
gridToBattery = datKWH$gridToBattery

# Common plot theme
sharedTheme = theme_minimal()
# Change the appearance of the main title
sharedTheme = sharedTheme + theme(plot.title = element_text(size=18, face="bold",margin = margin(10, 0, 10, 0)))

g = ggplot(datKWH, aes(x = timestamp, y = gridToBattery)) 
g = g + geom_point() + geom_line()
g = g + ggtitle("Power generated by solar in January 2019") + xlab("Time") + ylab("Grid To Battery, kWh")
g = g + sharedTheme
# scale_*_datetime for datetimes (class POSIXct),
# g = g + scale_x_datetime(breaks='1 week', labels = "%W")
# g = g + coord_cartesian(ylim = c(0, max(datKWH[, 'gridToBattery'])))

print(g)

# Summarize gridToBattery by hour, day and week:
datKWH %>% group_by(timestamp=floor_date(timestamp, "hour")) %>%
  summarize(gridToBattery=sum(gridToBattery))
datKWH %>% group_by(timestamp=floor_date(timestamp, "day")) %>%
  summarize(gridToBattery=sum(gridToBattery))
datKWH %>% group_by(timestamp=floor_date(timestamp, "week")) %>%
  summarize(gridToBattery=sum(gridToBattery))