setwd(paste(default, "plots\\", sep=""))

colJA = c("#52A9AD","#98B4EC", "#B2C1F6", "#E7BFFF", "#A1E082")
names(colJA) <- c("R13JA", "D13JA", "D40JA", "D90JA", "A13JA")
colLG = c("#1C3738", "#3A45B7", "#6874E8", "#725AC1", "#3DA35D")
names(colLG) <- c("R13LG", "D13LG", "D40LG", "D90LG", "A13LG")
colPan <- append(colJA, colLG)

month = tolower(month(min(datSol$timestamp), label=TRUE))
baseTitle = ggtitle("Energy generated by each solar panel")
cumTitle = ggtitle("Cumulative energy generated by each solar panel")
colScale <- scale_colour_manual(name="panel", values=colPan)
fillScale = scale_fill_manual(name="panel", values=colPan)

p = ggplot(sumDays2, aes(x=day, y=Wh, color=panel)) + geom_point() +
    theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle + colScale 

p1 = p
ggsave(paste(month, "wh", "all", extension, sep=""), width = width, height = height, units = "cm")

p2 <- p %+% droplevels(subset(sumDays2, panel=="D40JA" | panel=="D40LG")) 
ggsave(paste(month, "wh", "D40", extension, sep=""), width = width, height = height, units = "cm")
p2 <- p %+% droplevels(subset(sumDays2, panel=="D90JA" | panel=="D90LG"))
ggsave(paste(month, "wh", "D90", extension, sep=""), width = width, height = height, units = "cm")
p2 <- p %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="D13LG"))
ggsave(paste(month, "wh", "D13", extension, sep=""), width = width, height = height, units = "cm")
p2 <- p %+% droplevels(subset(sumDays2, panel=="A13JA" | panel=="A13LG"))
ggsave(paste(month, "wh", "A13", extension, sep=""), width = width, height = height, units = "cm")
p2 <- p %+% droplevels(subset(sumDays2, panel=="R13JA" | panel=="R13LG"))
ggsave(paste(month, "wh", "R13", extension, sep=""), width = width, height = height, units = "cm")

b = ggplot(sumDays2, aes(x=day, y=Wh, fill=panel)) + geom_bar(stat = "identity") +
    theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle + fillScale
ggsave(paste(month, "wh", "all", "bar", extension, sep=""), width = width, height = height, units = "cm")

b1 = ggplot(sumDays2, aes(x=day, y=Wh, fill=panel)) + geom_bar(stat = "identity", position=position_dodge()) +
    theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle + fillScale

b2 = b1 %+% droplevels(subset(sumDays2, panel=="D40JA" | panel=="D40LG")) 
ggsave(paste(month, "wh", "D40", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D90JA" | panel=="D90LG"))
ggsave(paste(month, "wh", "D90", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="D13LG"))
ggsave(paste(month, "wh", "D13", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="A13JA" | panel=="A13LG"))
ggsave(paste(month, "wh", "A13", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="R13JA" | panel=="R13LG"))
ggsave(paste(month, "wh", "R13", "bar", extension, sep=""), width = width, height = height, units = "cm")

b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="D40JA" | panel=="D90JA"))
ggsave(paste(month, "wh", "DJA", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D13LG" | panel=="D40LG" | panel=="D90LG"))
ggsave(paste(month, "wh", "DLG", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="D40JA" | panel=="D90JA"))
ggsave(paste(month, "wh", "DJA", "2", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b %+% droplevels(subset(sumDays2, panel=="D13LG" | panel=="D40LG" | panel=="D90LG"))
ggsave(paste(month, "wh", "DLG", "2", "bar", extension, sep=""), width = width, height = height, units = "cm")

b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="R13JA" | panel=="A13JA"))
ggsave(paste(month, "wh", "13JA", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b1 %+% droplevels(subset(sumDays2, panel=="D13LG" | panel=="R13LG" | panel=="A13LG"))
ggsave(paste(month, "wh", "13LG", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b %+% droplevels(subset(sumDays2, panel=="D13JA" | panel=="R13JA" | panel=="A13JA"))
ggsave(paste(month, "wh", "13JA", "2", "bar", extension, sep=""), width = width, height = height, units = "cm")
b2 <- b %+% droplevels(subset(sumDays2, panel=="D13LG" | panel=="R13LG" | panel=="A13LG"))
ggsave(paste(month, "wh", "13LG", "2", "bar", extension, sep=""), width = width, height = height, units = "cm")

# # week
# p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
#     geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
#     geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
#     geom_point(aes(y = D40JA, col = "D40JA", shape = "D40JA")) +
#     geom_point(aes(y = D40LG, col = "D40LG", shape = "D40LG")) +
#     geom_point(aes(y = D90JA, col = "D90JA", shape = "D90JA")) +
#     geom_point(aes(y = D90LG, col = "D90LG", shape = "D90LG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
#     theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle
# ggsave(paste("weekWH_D", extension, sep=""), width = width, height = height, units = "cm")
# 
# p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
#     geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
#     geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
#     geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
#     geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
#     geom_point(aes(y = R13JA, col ="R13JA", shape = "R13JA")) +
#     geom_point(aes(y = R13LG, col = "R13LG", shape = "R13LG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
#     theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle
# ggsave(paste("weekWH_13", extension, sep=""), width = width, height = height, units = "cm")
# 
# p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
#     geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
#     geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
#     theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle
# ggsave(paste("weekWH_A13", extension, sep=""), width = width, height = height, units = "cm")
# 
# p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
#     geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
#     geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
#     theme_minimal() + xlab("Day") + ylab("Wh") + baseTitle
# ggsave(paste("weekWH_D13", extension, sep=""), width = width, height = height, units = "cm")
# 
# # base <- ggplot(sumDays, aes(x = day, y = D40JA)) +
# #     geom_blank() +
# #     xlab("Day") +
# #     ylab("Wh")
# 
# p = ggplot(cumSumDays, aes(x=day, y=value, color = variable)) +
#     geom_line(aes(y = A13JA/1000, col = "A13JA")) +
#     geom_line(aes(y = A13LG/1000, col = "A13LG")) +
#     geom_line(aes(y = D13JA/1000, col = "D13JA")) +
#     geom_line(aes(y = D13LG/1000, col = "D13LG")) +
#     geom_line(aes(y = R13JA/1000, col ="R13JA")) +
#     geom_line(aes(y = R13LG/1000, col = "R13LG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
#     theme_minimal() + xlab("Day") + ylab("kWh") + cumTitle
# ggsave(paste("cum_dayKWH_13", extension, sep=""), width = width, height = height, units = "cm")