setwd(paste(default, "plots\\", sep=""))
# m = ggplot(datMeteo, aes(x=timestamp, y=value, color = variable, shape = variable)) +
#     geom_line(aes(y = solarIrradiance*1.63515, col = "solarIrradianceJA", shape = "solarIrradianceJA")) +
#     geom_line(aes(y = solarIrradiance*1.7272, col = "solarIrradianceLG", shape = "solarIrradianceLG")) +
#     scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
#     theme_minimal() + xlab("Timestamp") + ylab("Watts/ Panel area") + ggtitle("Solar irradiance")
# ggsave(paste("meteo", extension, sep=""), width = width, height = height, units = "cm")

p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = D40JA, col = "D40JA", shape = "D40JA")) +
    geom_point(aes(y = D40LG, col = "D40LG", shape = "D40LG")) +
    geom_point(aes(y = D40JA, col = "D90JA", shape = "D90JA")) +
    geom_point(aes(y = D40LG, col = "D90LG", shape = "D90LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayWH_D", extension, sep=""), width = width, height = height, units = "cm")
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D13JA/1000, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG/1000, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = D40JA/1000, col = "D40JA", shape = "D40JA")) +
    geom_point(aes(y = D40LG/1000, col = "D40LG", shape = "D40LG")) +
    geom_point(aes(y = D40JA/1000, col = "D90JA", shape = "D90JA")) +
    geom_point(aes(y = D40LG/1000, col = "D90LG", shape = "D90LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("kWh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayKWH_D", extension, sep=""), width = width, height = height, units = "cm")
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
    geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = R13JA, col ="R13JA", shape = "R13JA")) +
    geom_point(aes(y = R13LG, col = "R13LG", shape = "R13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayWH_13", extension, sep=""), width = width, height = height, units = "cm")
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = A13JA/1000, col = "A13JA", shape = "A13JA")) +
    geom_point(aes(y = A13LG/1000, col = "A13LG", shape = "A13LG")) +
    geom_point(aes(y = D13JA/1000, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG/1000, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = R13JA/1000, col ="R13JA", shape = "R13JA")) +
    geom_point(aes(y = R13LG/1000, col = "R13LG", shape = "R13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("kWh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayKWH_13", extension, sep=""), width = width, height = height, units = "cm")
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
    geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayKWH_A13", extension, sep=""), width = width, height = height, units = "cm")
# ######################
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayKWH_D13", extension, sep=""), width = width, height = height, units = "cm")
p = ggplot(sumDays, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D90JA, col = "D90JA", shape = "D90JA")) +
    geom_point(aes(y = D90LG, col = "D90LG", shape = "D90LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("dayKWH_D90", extension, sep=""), width = width, height = height, units = "cm")
##################
sumDayJA = data.frame("day" = sumDays$day, "type" = rep("JA", each = nrow(sumDays)), "Wh" = sumDays$D90JA)
sumDayLG = data.frame("day" = sumDays$day, "type" = rep("LG", each = nrow(sumDays)),"Wh" = sumDays$D90LG)
# sumD90 = bind_rows(sumDayJA,sumDayLG)
sumD90 = rbind(sumDayJA,sumDayLG)
p = ggplot(sumD90, aes(x=day, y=Wh, fill = type)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh")
ggsave(paste("dayWH_D90bar", extension, sep=""), width = width, height = height, units = "cm")

sumDayJA = data.frame("day" = sumDays$day, "type" = rep("JA", each = nrow(sumDays)), "Wh" = sumDays$D40JA)
sumDayLG = data.frame("day" = sumDays$day, "type" = rep("LG", each = nrow(sumDays)),"Wh" = sumDays$D40LG)
# sumD90 = bind_rows(sumDayJA,sumDayLG)
sumD40 = rbind(sumDayJA,sumDayLG)
p = ggplot(sumD40, aes(x=day, y=Wh, fill = type)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh")
ggsave(paste("dayWH_D40bar", extension, sep=""), width = width, height = height, units = "cm")

sumDayJA = data.frame("day" = sumDays$day, "type" = rep("JA", each = nrow(sumDays)), "Wh" = sumDays$D13JA)
sumDayLG = data.frame("day" = sumDays$day, "type" = rep("LG", each = nrow(sumDays)),"Wh" = sumDays$D13LG)
# sumD90 = bind_rows(sumDayJA,sumDayLG)
sumD13 = rbind(sumDayJA,sumDayLG)
p = ggplot(sumD13, aes(x=day, y=Wh, fill = type)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh")
ggsave(paste("dayWH_D13bar", extension, sep=""), width = width, height = height, units = "cm")

sumDayJA = data.frame("day" = sumDays$day, "type" = rep("JA", each = nrow(sumDays)), "Wh" = sumDays$R13JA)
sumDayLG = data.frame("day" = sumDays$day, "type" = rep("LG", each = nrow(sumDays)),"Wh" = sumDays$R13LG)
# sumD90 = bind_rows(sumDayJA,sumDayLG)
sumR13 = rbind(sumDayJA,sumDayLG)
p = ggplot(sumR13, aes(x=day, y=Wh, fill = type)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh")
ggsave(paste("dayWH_R13bar", extension, sep=""), width = width, height = height, units = "cm")

sumDayJA = data.frame("day" = sumDays$day, "type" = rep("JA", each = nrow(sumDays)), "Wh" = sumDays$A13JA)
sumDayLG = data.frame("day" = sumDays$day, "type" = rep("LG", each = nrow(sumDays)),"Wh" = sumDays$A13LG)
# sumD90 = bind_rows(sumDayJA,sumDayLG)
sumA13 = rbind(sumDayJA,sumDayLG)
p = ggplot(sumA13, aes(x=day, y=Wh, fill = type)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh")
ggsave(paste("dayWH_A13bar", extension, sep=""), width = width, height = height, units = "cm")

# week
p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = D40JA, col = "D40JA", shape = "D40JA")) +
    geom_point(aes(y = D40LG, col = "D40LG", shape = "D40LG")) +
    geom_point(aes(y = D90JA, col = "D90JA", shape = "D90JA")) +
    geom_point(aes(y = D90LG, col = "D90LG", shape = "D90LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("weekWH_D", extension, sep=""), width = width, height = height, units = "cm")

p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
    geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    geom_point(aes(y = R13JA, col ="R13JA", shape = "R13JA")) +
    geom_point(aes(y = R13LG, col = "R13LG", shape = "R13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 6)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("weekWH_13", extension, sep=""), width = width, height = height, units = "cm")

p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = A13JA, col = "A13JA", shape = "A13JA")) +
    geom_point(aes(y = A13LG, col = "A13LG", shape = "A13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("weekWH_A13", extension, sep=""), width = width, height = height, units = "cm")

p = ggplot(sumWeeks, aes(x=day, y=value, color = variable, shape = variable)) +
    geom_point(aes(y = D13JA, col = "D13JA", shape = "D13JA")) +
    geom_point(aes(y = D13LG, col = "D13LG", shape = "D13LG")) +
    scale_color_manual(values = wes_palette("BottleRocket1", 2)) +
    theme_minimal() + xlab("Day") + ylab("Wh") + ggtitle("Power generated by each solar panel")
ggsave(paste("weekWH_D13", extension, sep=""), width = width, height = height, units = "cm")

base <- ggplot(sumDays, aes(x = day, y = D40JA)) +
    geom_blank() +
    xlab("Day") +
    ylab("Wh")